---
fixtures:
  repositories:
    stdlib:
      ref: "4.24.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    docker:
      ref: "3.5.0"
      repo: "https://github.com/puppetlabs/puppetlabs-docker"
    apt:
      ref: "5.0.1"
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
  symlinks:
    vision_docker: '#{source_dir}'
