---
fixtures:
    repositories:
        stdlib:
            ref: "4.12.0"
            repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
        docker:
            ref: "v5.3.0"
            repo: "https://github.com/garethr/garethr-docker"
        apt:
            ref: "2.2.2"
            repo: "https://github.com/puppetlabs/puppetlabs-apt"
    symlinks:
        vision_docker: '#{source_dir}'
