sudo: false
language: ruby
cache: bundler
rvm: 2.3
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  allow_failures:
    - env: STRICT_VARIABLES="yes" CHECK="rubocop"
      bundler_args: --without testing acceptance
  include:
    - env: STRICT_VARIABLES="yes" CHECK="rubocop"
      bundler_args: --without testing acceptance
    - env: STRICT_VARIABLES="yes" CHECK="lint"
      bundler_args: --without rubocop acceptance
    - env: STRICT_VARIABLES="yes" CHECK="validate"
      bundler_args: --without rubocop acceptance
    - env: STRICT_VARIABLES="yes" CHECK="spec"
      bundler_args: --without rubocop acceptance
    - env: STRICT_VARIABLES="yes" CHECK="beaker" BEAKER_set="debian9"
      services: docker
      sudo: required
    - env: STRICT_VARIABLES="yes" CHECK="beaker" BEAKER_set="debian10"
      before_script: sh ./buster_fix.sh
      services: docker
      sudo: required
notifications:
  email: false
